function Hd = filterChebyshevII_p2
%FILTERCHEBYSHEVII_P2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 11-Sep-2023 15:22:04

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

N     = 3;    % Order
Fstop = 0.5;  % Stopband Frequency
Astop = 40;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass('N,Fst,Ast', N, Fstop, Astop);
Hd = design(h, 'cheby2');

% [EOF]
