function Hd = filterInterpolation_p1
%FILTERINTERPOLATION_P1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 12-Sep-2023 14:09:37

% Interpolated FIR Lowpass filter designed using the IFIR function.

% All frequency values are normalized to 1.

Fpass = 0.01;        % Passband Frequency
Fstop = 0.12;        % Stopband Frequency
Dpass = 0.7;         % Passband Ripple
Dstop = 0.1;         % Stopband Attenuation
L     = 4;           % Interpolation Factor
optim = 'Advanced';  % Optimization Level

% Calculate the coefficients using the IFIR function.
[h, g] = ifir(L, 'low', [Fpass Fstop], [Dpass Dstop], optim);
Hd     = cascade(dfilt.dffir(h), dfilt.dffir(g));

% [EOF]
