function Hd = filterLeastPth_Norm_p1
%FILTERLEASTPTH-NORM_P1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 11-Sep-2023 17:12:18

% IIR Least P-th norm Lowpass filter designed using the IIRLPNORM function.

% All frequency values are normalized to 1.

Nb    = 1;                    % Numerator Order
Na    = 8;                    % Denominator Order
Fpass = 0.10000000000000001;  % Passband Frequency
Fstop = 0.5;                  % Stopband Frequency
Wpass = 0.5;                  % Passband Weight
Wstop = 0.5;                  % Stopband Weight
P     = [2 10];               % P'th norm
dens  = 20;                   % Density Factor

F = [0 Fpass Fstop 1];

% Calculate the coefficients using the IIRLPNORM function.
[b,a,err,sos_var,g] = iirlpnorm(Nb, Na, F, F, [1 1 0 0], [Wpass Wpass ...
                                Wstop Wstop], P, {dens});
Hd                  = dfilt.df2sos(sos_var, g);

% [EOF]
