function Hd = filterEquiripple_p6
%FILTEREQUIRIPPLE_P6 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 11-Sep-2023 17:47:31

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 6;     % Order
Fpass = 0.05;  % Passband Frequency
Fstop = 0.5;   % Stopband Frequency
Wpass = 0.1;   % Passband Weight
Wstop = 0.9;   % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
Hd = dfilt.dffir(b);

% [EOF]
