function Hd = filterEquiripple_p8
%FILTEREQUIRIPPLE_P8 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 12-Sep-2023 12:59:41

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 3;     % Order
Fpass = 0.09;  % Passband Frequency
Fstop = 0.5;   % Stopband Frequency
Wpass = 0.2;   % Passband Weight
Wstop = 0.9;   % Stopband Weight
dens  = 50;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
Hd = dfilt.dffir(b);

% [EOF]
