function Hd = filterMaximallyFlatFIR_p4
%FILTERMAXIMALLYFLATFIR_P4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 14-Sep-2023 16:03:23

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are normalized to 1.

N  = 2;    % Order
Fc = 0.1;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc);
Hd                    = dfilt.df2sos(sos_var, g);

% [EOF]
