function Hd = filterWindowChebyshev_p2
%FILTERWINDOWCHEBYSHEV_P2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 12-Sep-2023 13:27:34

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N             = 3;          % Order
Fc            = 0.655;      % Cutoff Frequency
flag          = 'noscale';  % Sampling Flag
SidelobeAtten = 120;        % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc, 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
