function Hd = filterLeastSquares_p11
%FILTERLEASTSQUARES_P0 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 14-Sep-2023 14:49:39

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N     = 3;     % Order
Fpass = 0.3;   % Passband Frequency
Fstop = 0.6;   % Stopband Frequency
Wpass = 0.02;  % Passband Weight
Wstop = 0.98;  % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
