function Hd = filterLeastSquares_p2
%FILTERLEASTSQUARES_P2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 11-Sep-2023 17:55:52

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N     = 3;    % Order
Fpass = 0.2;  % Passband Frequency
Fstop = 0.5;  % Stopband Frequency
Wpass = 0.3;  % Passband Weight
Wstop = 0.9;  % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
