function Hd = filterMaximallyFlat_p1
%FILTERMAXIMALLYFLAT_P1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 11-Sep-2023 17:01:18

% IIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are normalized to 1.

Nb   = 8;    % Numerator Order
Na   = 8;    % Denominator Order
F3dB = 0.9;  % 3-dB Frequency

h  = fdesign.lowpass('Nb,Na,F3dB', Nb, Na, F3dB);
Hd = design(h, 'butter');

% [EOF]
