function Hd = filterButterworth_p0
%FILTERBUTTERWORTH_P0 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 07-Sep-2023 11:20:19

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 361;  % Sampling Frequency

Fpass = 170.5;       % Passband Frequency
Fstop = 175.5;       % Stopband Frequency
Apass = 30;          % Passband Ripple (dB)
Astop = 100;         % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
