function Hd = filterEquiripple_p3
%FILTEREQUIRIPPLE_P3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 11-Sep-2023 17:38:58

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 3;    % Order
Fpass = 0.1;  % Passband Frequency
Fstop = 0.5;  % Stopband Frequency
Wpass = 0.7;  % Passband Weight
Wstop = 0.3;  % Stopband Weight
dens  = 100;  % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
Hd = dfilt.dffir(b);

% [EOF]
