function Hd = filterInterpolation_p2
%FILTERINTERPOLATION_P2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 14-Sep-2023 15:13:53

% Interpolated FIR Lowpass filter designed using the IFIR function.

% All frequency values are normalized to 1.

Fpass = 0.1;   % Passband Frequency
Fstop = 0.21;  % Stopband Frequency
Dpass = 0.3;   % Passband Ripple
Dstop = 0.3;   % Stopband Attenuation
L     = 4;     % Interpolation Factor

% Calculate the coefficients using the IFIR function.
[h, g] = ifir(L, 'low', [Fpass Fstop], [Dpass Dstop]);
Hd     = cascade(dfilt.dffir(h), dfilt.dffir(g));

% [EOF]
