function Hd = filterLeastSquares_p4
%FILTERLEASTSQUARES_P4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 12-Sep-2023 11:42:12

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N     = 3;     % Order
Fpass = 0.3;   % Passband Frequency
Fstop = 0.5;   % Stopband Frequency
Wpass = 0.05;  % Passband Weight
Wstop = 0.95;  % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
