{
 "title": "USV-APRS",
 "description": "APRS Visualisierung des USV-Nordwind",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kurs",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "usv", "table": "gps" }
   ]
  },
  {
   "title": "Kurs",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.sb6 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.sb5 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 1",
   "type": "stat",
   "description": "Spannung Akku 1",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 2",
   "type": "stat",
   "description": "Spannung Akku 2",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em4 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lidar",
   "type": "stat",
   "description": "Spannung Lidar",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em9 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 11, "w": 1, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.sb1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 1",
   "type": "stat",
   "description": "Strom Akku 1",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em2 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 2",
   "type": "stat",
   "description": "Strom Akku 2",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em5 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Solar",
   "type": "stat",
   "description": "Ladespannung",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em7 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 1",
   "type": "stat",
   "description": "Kapazität Akku 1",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em3 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Akku 2",
   "type": "stat",
   "description": "Kapazität Akku 2",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em6 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "description": "Boradtemperatur",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.em8 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Schub",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.as1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Ruder",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "usv",
     "rawSql": "SELECT Messung FROM usv.as2 LIMIT 50 "
    }
   ]
  }
 ]
}