/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 15-Sep-2023 10:53:10
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
//here modified
#include "stdint.h"
/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
extern const int mf_NumeratorLen = 3;//here modified
extern const uint16_t mf_Numerator[3] = {//here modified
     8192,  16384,   8192
};
extern const int mf_DenominatorLen = 3;//here modified
extern const uint16_t mf_Denominator[3] = {//here modified
    32768,      0,      0
};
