/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 15-Sep-2023 10:56:23
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 4
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
//here modified
#include "stdint.h"
/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
const int wk_NumeratorLen = 4;//here modified
const uint16_t wk_Numerator[4] = {//here modified
     1662,  14722,  14722,   1662
};
