/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 22-Sep-2023 15:58:16
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h 
 */
const int mf_numLen = 3;
const real64_T mf_num[3] = {
                0.25,               0.5,              0.25
};
const int mf_denLen = 3;
const real64_T mf_den[3] = {
                   1,                 0,                 0
};
