/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 22-Sep-2023 16:08:12
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 4
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h 
 */
const int wt_numLen = 4;
const real64_T wt_num[4] = {
    0.09733599298991,   0.4026640070101,   0.4026640070101,  0.09733599298991
};
