#ifndef FILTERCONFIG_H_INCLUDED
#define FILTERCONFIG_H_INCLUDED

#define FIXED_POINT_BITS 15
#define CONVERT_FACTOR_INT ((1<<FIXED_POINT_BITS) - 1)
#define OUTPUT_MAX_LEN 512

#endif // FILTERCONFIG_H_INCLUDED
